---

###############################################################################
# connection settings
###############################################################################

connection:
  # The URL to use to connect to the Dukascopy platform.
  #
  # Example for the DEMO environment: http://platform.dukascopy.com/demo/jforex.jnlp
  url: 'http://platform.dukascopy.com/demo/jforex.jnlp'
  # The username to use.
  username: '__________'
  # The password to use.
  password: '__________'

# The instruments to use, can use both EURUSD notation and EUR/USD
#
# Instruments:
# EUR/USD
# XAU/USD
# GBP/USD
# AUD/USD
instruments:
  - 'AUD/CAD'
  - 'AUD/CHF'
  - 'AUD/JPY'
  - 'AUD/NZD'
  - 'AUD/USD'
  - 'CAD/CHF'
  - 'CAD/JPY'
  - 'EUR/AUD'
  - 'EUR/CHF'
  - 'EUR/JPY'
  - 'EUR/USD'
  - 'EUR/CAD'
  - 'EUR/GBP'
  - 'GBP/AUD'
  - 'GBP/CAD'
  - 'GBP/CHF'
  - 'GBP/JPY'
  - 'GBP/NZD'
  - 'GBP/USD'
  - 'NZD/CAD'
  - 'NZD/CHF'
  - 'NZD/JPY'
  - 'NZD/USD'
  - 'USD/CAD'
  - 'USD/JPY'
  - 'USD/CHF'
  - 'USD/HKD'
  - 'USD/SGD'
  - 'USD/CHF'

